class ParseErrors {
  static final Map<int, String> _error = {
    -1: 'Unknown error',
    1: 'Internal Server Error (InternalServerError)',
    100: 'Connection to the server failed (ConnectionFailed)',
    101: 'Invalid username / password',
    102: 'Invalid query (InvalidQuery)',
    103: 'Invalid Class Name (InvalidClassName)',
    104: 'Object ID not found (MissingObjectId)',
    105: 'Invalid key name (InvalidKeyName)',
    106: 'Invalid pointer (InvalidPointer)',
    107: 'Invalid JSON (InvalidJSON)',
    108: 'Resource unavailable (CommandUnavailable)',
    109: 'Parse not initialized (NotInitialized)',
    111: 'Field with incorrect type (IncorrectType)',
    112: 'Invalid channel (InvalidChannelName)',
    115: 'Push configured incorrectly (PushMisconfigured)',
    116: 'Object is too big (ObjectTooLarge)',
    119: 'Operation is not allowed for the Client (OperationForbidden)',
    120: 'Result not found in cache (CacheMiss)',
    121: 'Invalid key in a JSON (InvalidNestedKey)',
    122: 'Invalid file name in ParseFile (InvalidFileName)',
    123: 'Invalid ACL (InvalidACL)',
    124: 'Timeout (InvalidACL)',
    125: 'Invalid email',
    137: 'Duplicate value for exclusive field',
    139: 'Invalid function name (InvalidRoleName)',
    140: 'Application quota exceeded (ExceededQuota)',
    141: 'Cloudcode script (ScriptFailed) failed',
    142: 'Cloudcode validation failed (ValidationFailed)',
    153: 'File deletion failed (FileDeleteFailed)',
    155: 'The application has exceeded its request limit (RequestLimitExceeded)',
    160: 'Invalid event (InvalidEventName)',
    200: 'Username was not filled in',
    201: 'Password was not filled in',
    202: 'Informed email already exists. Please enter another email ',
    203: 'Informed email already exists. Please enter another email ',
    204: 'E-mail has not been filled in',
    205: 'E-mail is not registered',
    206: 'Invalid session for changing the user (SessionMissing)',
    207: 'User can only be created via Signup (MustCreateUserThroughSignup)',
    208: 'The reported account is already linked to another user',
    209: 'Invalid session (InvalidSessionToken)',
    250: 'User cannot be linked to an account because the ID was not found (InvalidSessionToken)',
    251: 'User with linked account is having an invalid session (InvalidLinkedSession)',
    252: 'Service being linked is not supported (UnsupportedService)',
  };

  static String getDescription(int error) {
    return _error[error];
  }
}
